version: '2'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
       - "database"
    links:
      - database:container-mysql
    command: [ "./wait-for-it.sh","container-mysql:3306","-t", "60", "--", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]

  redis:
    image: "redis:alpine"

  database:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose
    volumes:
      - ./db/mysql-data:/var/lib/mysql
      - ./db/db_create.sql:/tmp/dbcreation.sql
      - ./db/import.sh:/tmp/import.sh
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db_example"
      MYSQL_USER: "springuser"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    depends_on:
      - "redis"
